stages:
  - test
  - build

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  before_script:
    - dotnet restore
  script:
    - dotnet test
  only:
    - merge_requests
    - branches
    
benchmark:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  before_script:
    - dotnet restore
  script:
    - dotnet run -c Release --project Chart.Core.Parsers.Benchmarks/Chart.Core.Parser.Benchmarks.csproj
    - cat "BenchmarkDotNet.Artifacts/results/Chart.Core.Parsers.Benchmarks.SchemaParserBenchmark-report.metrics" > metrics.txt
  artifacts:
    reports:
      metrics: metrics.txt
  only:
    - merge_requests
