name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  spellcheck:
    name: "Spellcheck Documentation"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install cSpell
      run: npm install -g cspell

    - name: Run cSpell
      run: cspell --config ./cSpell.json "docs/**/*.md" --no-progress