name: Pull requests

on:
  pull_request_target:
    branches:
      - main

jobs:
  pr-labeler:
    name: Apply labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  test:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: | 
              6.0.x
              7.0.x

      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}

      - name: Code linting
        run: ./build.cmd Format

      - name: Run test suite
        run: ./build.cmd Test